#Do not edit this file, it is generated automatically.
class_name MainMessage extends Resource

@export var int_value: int
@export var string_value: String
@export var int_vec: Array[int]
@export var string_vec: Array[String]

func _init():
	set_meta('bsatn_type_int_value', &'u8')
	set_meta('bsatn_type_int_vec', &'u8')

static func create(_int_value: int, _string_value: String, _int_vec: Array[int], _string_vec: Array[String]) -> MainMessage:
	var result = MainMessage.new()
	result.int_value = _int_value
	result.string_value = _string_value
	result.int_vec = _int_vec
	result.string_vec = _string_vec
	return result