#Do not edit this file, it is generated automatically.
class_name MainDamage extends Resource

@export var amount: int
@export var source: PackedByteArray
@export var int_vec: Array[int]

func _init():
	set_meta('bsatn_type_amount', &'u32')
	set_meta('bsatn_type_source', &'identity')
	set_meta('bsatn_type_int_vec', &'u8')

static func create(_amount: int, _source: PackedByteArray, _int_vec: Array[int]) -> MainDamage:
	var result = MainDamage.new()
	result.amount = _amount
	result.source = _source
	result.int_vec = _int_vec
	return result
