#Do not edit this file, it is generated automatically.
class_name MainModule extends Resource

const Lobby = preload('res://schema/tables/main_lobby.gd')
const Message = preload('res://schema/spacetime_types/main_message.gd')
const User = preload('res://schema/tables/main_user.gd')
const Damage = preload('res://schema/spacetime_types/main_damage.gd')
const UserData = preload('res://schema/tables/main_user_data.gd')
const Reducers = preload('res://schema/module_main_reducers.gd')

static func change_color_random(cb: Callable = func(_t: TransactionUpdateData): pass) -> void:
	var _id: int = SpacetimeDB.call_reducer('change_color_random', [], [])
	var _result = await SpacetimeDB.wait_for_reducer_response(_id)
	cb.call(_result)

static func move_user(new_input: Vector2, global_position: Vector3, cb: Callable = func(_t: TransactionUpdateData): pass) -> void:
	var _id: int = SpacetimeDB.call_reducer('move_user', [new_input, global_position], ['', ''])
	var _result = await SpacetimeDB.wait_for_reducer_response(_id)
	cb.call(_result)

static func save_my_bytes(bytes: Array[int], cb: Callable = func(_t: TransactionUpdateData): pass) -> void:
	var _id: int = SpacetimeDB.call_reducer('save_my_bytes', [bytes], [&'u8'])
	var _result = await SpacetimeDB.wait_for_reducer_response(_id)
	cb.call(_result)

static func test_struct(message: MainMessage, another_message: MainMessage, cb: Callable = func(_t: TransactionUpdateData): pass) -> void:
	var _id: int = SpacetimeDB.call_reducer('test_struct', [message, another_message], [&'MainMessage', &'MainMessage'])
	var _result = await SpacetimeDB.wait_for_reducer_response(_id)
	cb.call(_result)
