#Do not edit this file, it is generated automatically.
class_name MainModule extends Resource

const Lobby = preload('res://schema/tables/main_lobby.gd')
const Message = preload('res://schema/spacetime_types/main_message.gd')
const User = preload('res://schema/tables/main_user.gd')
const Damage = preload('res://schema/spacetime_types/main_damage.gd')
const UserData = preload('res://schema/tables/main_user_data.gd')
const Reducers = preload('res://schema/module_main_reducers.gd')
