#Do not edit this file, it is generated automatically.
class_name MainLobby extends _ModuleTable

const table_names: Array[String] = ['lobby']

@export var id: int
@export var player_count: int

func _init():
	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_player_count', &'u32')

static func create(_id: int, _player_count: int) -> MainLobby:
	var result = MainLobby.new()
	result.id = _id
	result.player_count = _player_count
	return result
