#Do not edit this file, it is generated automatically.
class_name MainUser extends Resource

@export var identity: PackedByteArray
@export var online: bool
@export var lobby_id: int
@export var damage: MainDamage

func _init():
	set_meta('table_name', 'user')
	set_meta('primary_key', 'identity')
	set_meta('bsatn_type_identity', &'identity')
	set_meta('bsatn_type_lobby_id', &'u64')
	set_meta('bsatn_type_damage', &'MainDamage')

static func create(_identity: PackedByteArray, _online: bool, _lobby_id: int, _damage: MainDamage) -> MainUser:
	var result = MainUser.new()
	result.identity = _identity
	result.online = _online
	result.lobby_id = _lobby_id
	result.damage = _damage
	return result
